### PR TITLE
Use random text for naming product and category in the testings

### PR DESCRIPTION
**Pull request by mplt-aleks**

### CODE REVIEW

**Comment by mplt-aleks** [comment]
@mplt-simon update the tests to use e() for user->name assertions. 👍

**Comment by mplt-simon** [comment]
@mplt-aleks Brilliant, thanks

**Comment by mplt-aleks** [comment]
@mplt-simon another revision to solve testing issues for user's name

**Review by mplt-simon — APPROVED** [review]
Testing ok for me locally now 👍

**Pull request merged**
