### PR TITLE
Handle user multiple role

### PR DESCRIPTION
**Pull request by mplt-aleks**
To address issue: https://github.com/motorpilotltd/feedback-tool/issues/28
- Should now allow to assign multiple roles for a user
- Prioritize super admin role 
- Added new tests for user role/permissions table

### CODE REVIEW

**Comment by mplt-aleks** [comment]
@mplt-simon this is now ready for review, we could wait for the Laravel 11.19.0 Shift #33 to be merge first to main then rebase this branch before approving.

**Comment by mplt-simon** [comment]
I've merged the 11.19.0 Shift branch to main so all good for you to rebase 👍

**Comment by mplt-aleks** [comment]
@mplt-simon this is ready for review now. 👍

**Review by mplt-simon — APPROVED** [review]
All ooks good, and have tested locally to confirm.

**Review by mplt-simon — APPROVED** [review]
Post merge-base change - all still looks good and has been tested locally!

**Review by mplt-simon — APPROVED** [review]
All looks good, and have tested locally to confirm.

**Review by mplt-simon — APPROVED** [review]
All looks good, and have tested locally to confirm.

**Review by mplt-simon — APPROVED** [review]
All looks ok and tested locally.

**Pull request merged**
